### ISSUE TITLE
FR | Add check username in password

### ISSUE THREAD

**Issue by x09** [openwall/passwdqc#35]
if the password contains username (or few symbols in username) - password must not accepted.

Please add to config

_checkusername=true
checkusernamesymbols=3_

Example:
username=billgilbert
password=**BillGilbert**
result: failed (checkusername detected)

username=billgilbert
password=**bil**lpa$$word
result: failed (checkusernamesymbols detected)

username=billgilbert
password=pa$$word4**gil**bert
result: failed (checkusernamesymbols detected)

username=billgilbert
password=my-mom_called_me_**bil**ly
result: failed (checkusernamesymbols detected)

**Comment by solardiz** [comment]
We already have this feature, except that instead of rejecting the password right away we subject it to the rest of checks with the common substring virtually shortened to be just below the match threshold. Your example `my-mom_called_me_billy` probably contains enough unpredictability besides the weak substring `bill`. It would be illogical to allow the password `my-mom_called_me`, but disallow `my-mom_called_me_billy`.

```
        match=N                         [match=4]

The length of common substring required to conclude that a password is
at least partially based on information found in a character string,
or 0 to disable the substring search.  Note that the password will not
be rejected once a weak substring is found; it will instead be
subjected to the usual strength requirements with the weak substring
partially discounted.

The substring search is case-insensitive and is able to detect and
remove a common substring spelled backwards.
```
